schema: pokerheader.v1
project: pokertool
file: .github/.DS_Store
version: v28.0.0
last_commit: '2025-09-23T07:50:03.579381+00:00'
fixes:
- date: '2025-09-25'
  summary: Enhanced enterprise documentation and comprehensive unit tests added
