# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "georgeridout"
    labels:
      - "dependencies"
      - "python"
    # Group minor and patch updates together
    groups:
      development-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"
    # Ignore specific packages if needed
    # ignore:
    #   - dependency-name: "package-name"
    #     versions: ["1.x"]

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/pokertool-frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "georgeridout"
    labels:
      - "dependencies"
      - "frontend"
    groups:
      development-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"
    # Automatically rebase PRs when they become outdated
    rebase-strategy: "auto"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "georgeridout"
    labels:
      - "dependencies"
      - "github-actions"
