repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.1
  hooks:
    - id: ruff
      language: python
    - id: ruff
      language: python
      args: [ "check", "--fix", "--select", "I" ]
    - id: ruff-format
      language: python
- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v2.0.2
  hooks:
    - id: stylua-github
      language: lua
