# Pre-commit hooks for code quality
# See https://pre-commit.com for more information

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending

  # Python code formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length=100']

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length', '100']

  # Python linting with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [
          '--max-line-length=100',
          '--extend-ignore=E203,W503',  # Ignore whitespace conflicts with Black
          '--max-complexity=10'
        ]

  # Python type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: ['--config-file=mypy.ini']

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ['-c', '.bandit.yml']
        files: ^src/

  # Secret detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock.json

  # Dead code detection with vulture (warning only, non-blocking)
  - repo: local
    hooks:
      - id: vulture-check
        name: vulture (dead code detection)
        entry: bash -c 'vulture src/pokertool --min-confidence 80 --exclude tests/ || echo "⚠️  Dead code detected. See docs/DEAD_CODE_ANALYSIS.md for details. This is non-blocking."'
        language: system
        pass_filenames: false
        verbose: true

      - id: check-unused-imports
        name: check for unused imports (Python)
        entry: bash -c 'python3 -m autoflake --check --remove-all-unused-imports --recursive src/pokertool/ || echo "⚠️  Unused imports detected. Run: autoflake --remove-all-unused-imports --in-place --recursive src/pokertool/"'
        language: system
        types: [python]
        pass_filenames: false
        verbose: true

  # JavaScript/TypeScript formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown]
        args: ['--config', 'pokertool-frontend/.prettierrc']
        files: ^pokertool-frontend/

  # Python docstring checks
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ['--convention=google']
        files: ^src/

  # Check for common Python security issues
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
        files: requirements.txt

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: ['--fix']

# Configure pre-commit to run on all files on first setup
default_stages: [commit]
fail_fast: false
