apiVersion: v1
kind: Service
metadata:
  name: pokertool-service
  namespace: pokertool
  labels:
    app: pokertool
    component: backend
spec:
  selector:
    app: pokertool
    component: backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pokertool-postgres
  namespace: pokertool
  labels:
    app: pokertool
    component: database
spec:
  selector:
    app: pokertool
    component: database
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pokertool-redis
  namespace: pokertool
  labels:
    app: pokertool
    component: cache
spec:
  selector:
    app: pokertool
    component: cache
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
