name: Selene check

on:
  push:
    branches:
      - "main"
    paths:
      - "lua/**/*.lua"
      - "plugin/*.lua"
  pull_request:

jobs:
  selene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Selene check
        uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: lua/
          version: 0.28.0
