blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/Davidyz/VectorCode/discussions/new?category=q-a
    about: If you're new to VectorCode and is having trouble setting it up, post in discussions first. We can convert it to an issue if something's indeed wrong with VectorCode.
