// POKERTOOL-HEADER-START
// ---
// schema: pokerheader.v1
// project: pokertool
// file: src/shared/api/providers/vertex.ts
// version: v28.0.0
// last_commit: '2025-09-23T08:41:38+01:00'
// fixes:
// - date: '2025-09-25'
//   summary: Enhanced enterprise documentation and comprehensive unit tests added
// ---
// POKERTOOL-HEADER-END
import type { ModelInfo } from "../baseTypes"

// https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/use-claude
// https://cloud.google.com/vertex-ai/generative-ai/pricing#partner-models
export type VertexModelId = keyof typeof vertexModels
export const vertexDefaultModelId: VertexModelId = "claude-sonnet-4@20250514"
export const vertexModels = {
    "claude-sonnet-4@20250514": {
        maxTokens: 8192,
        contextWindow: 200_000,
        supportsImages: true,
        supportsPromptCache: true,
        inputPrice: 3.0,
        outputPrice: 15.0,
        cacheWritesPrice: 3.75,
        cacheReadsPrice: 0.3,
    },
    "claude-opus-4-1@20250805": {
        maxTokens: 8192,
        contextWindow: 200_000,
        supportsImages: true,
        supportsPromptCache: true,
        inputPrice: 15.0,
        outputPrice: 75.0,
        cacheWritesPrice: 18.75,
        cacheReadsPrice: 1.5,
    },
    "claude-opus-4@20250514": {
        maxTokens: 8192,
        contextWindow: 200_000,
        supportsImages: true,
        supportsPromptCache: true,
        inputPrice: 15.0,
        outputPrice: 75.0,
        cacheWritesPrice: 18.75,
        cacheReadsPrice: 1.5,
    },
    "claude-3-7-sonnet@20250219": {
        maxTokens: 8192,
        contextWindow: 200_000,
        supportsImages: true,
        supportsPromptCache: true,
        inputPrice: 3.0,
        outputPrice: 15.0,
        cacheWritesPrice: 3.75,
        cacheReadsPrice: 0.3,
        thinkingConfig: {
            maxBudget: 64000,
            outputPrice: 15.0,
        },
    },
    "claude-3-5-sonnet-v2@20241022": {
        maxTokens: 8192,
        contextWindow: 200_000,
        supportsImages: true,

        supportsPromptCache: true,
        inputPrice: 3.0,
        outputPrice: 15.0,
        cacheWritesPrice: 3.75,
        cacheReadsPrice: 0.3,
    },
    "claude-3-5-sonnet@20240620": {
        maxTokens: 8192,
        contextWindow: 200_000,
        supportsImages: true,
        supportsPromptCache: true,
        inputPrice: 3.0,
        outputPrice: 15.0,
        cacheWritesPrice: 3.75,
        cacheReadsPrice: 0.3,
    },
    "claude-3-5-haiku@20241022": {
        maxTokens: 8192,
        contextWindow: 200_000,
        supportsImages: false,
        supportsPromptCache: true,
        inputPrice: 1.0,
        outputPrice: 5.0,
        cacheWritesPrice: 1.25,
        cacheReadsPrice: 0.1,
    },
    "claude-3-opus@20240229": {
        maxTokens: 4096,
        contextWindow: 200_000,
        supportsImages: true,
        supportsPromptCache: true,
        inputPrice: 15.0,
        outputPrice: 75.0,
        cacheWritesPrice: 18.75,
        cacheReadsPrice: 1.5,
    },
    "claude-3-haiku@20240307": {
        maxTokens: 4096,
        contextWindow: 200_000,
        supportsImages: true,
        supportsPromptCache: true,
        inputPrice: 0.25,
        outputPrice: 1.25,
        cacheWritesPrice: 0.3,
        cacheReadsPrice: 0.03,
    },
    "mistral-large-2411": {
        maxTokens: 128_000,
        contextWindow: 128_000,
        supportsImages: false,
        supportsPromptCache: false,
        inputPrice: 2.0,
        outputPrice: 6.0,
    },
    "mistral-small-2503": {
        maxTokens: 128_000,
        contextWindow: 128_000,
        supportsImages: true,
        supportsPromptCache: false,
        inputPrice: 0.1,
        outputPrice: 0.3,
    },
    "codestral-2501": {
        maxTokens: 256_000,
        contextWindow: 256_000,
        supportsImages: false,
        supportsPromptCache: false,
        inputPrice: 0.3,
        outputPrice: 0.9,
    },
    "llama-4-maverick-17b-128e-instruct-maas": {
        maxTokens: 128_000,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsPromptCache: false,
        inputPrice: 0.35,
        outputPrice: 1.15,
    },
    "llama-4-scout-17b-16e-instruct-maas": {
        maxTokens: 1_000_000,
        contextWindow: 10_485_760,
        supportsImages: true,
        supportsPromptCache: false,
        inputPrice: 0.25,
        outputPrice: 0.7,
    },
    "gemini-2.0-flash-001": {
        maxTokens: 8192,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsPromptCache: true,
        supportsGlobalEndpoint: true,
        inputPrice: 0.15,
        outputPrice: 0.6,
        cacheWritesPrice: 1.0,
        cacheReadsPrice: 0.025,
    },
    "gemini-2.0-flash-lite-001": {
        maxTokens: 8192,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsPromptCache: false,
        supportsGlobalEndpoint: true,
        inputPrice: 0.075,
        outputPrice: 0.3,
    },
    "gemini-2.0-flash-thinking-exp-1219": {
        maxTokens: 8192,
        contextWindow: 32_767,
        supportsImages: true,
        supportsPromptCache: false,
        supportsGlobalEndpoint: true,
        inputPrice: 0,
        outputPrice: 0,
    },
    "gemini-2.0-flash-exp": {
        maxTokens: 8192,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsPromptCache: false,
        supportsGlobalEndpoint: true,
        inputPrice: 0,
        outputPrice: 0,
    },
    "gemini-2.5-pro-exp-03-25": {
        maxTokens: 65536,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsPromptCache: false,
        inputPrice: 0,
        outputPrice: 0,
    },
    "gemini-2.5-pro": {
        maxTokens: 65536,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsPromptCache: true,
        supportsGlobalEndpoint: true,
        inputPrice: 2.5,
        outputPrice: 15,
        cacheReadsPrice: 0.625,
        thinkingConfig: {
            maxBudget: 32767,
        },
        tiers: [
            {
                contextWindow: 200000,
                inputPrice: 1.25,
                outputPrice: 10,
                cacheReadsPrice: 0.31,
            },
            {
                contextWindow: Infinity,
                inputPrice: 2.5,
                outputPrice: 15,
                cacheReadsPrice: 0.625,
            },
        ],
    },
    "gemini-2.5-flash": {
        maxTokens: 65536,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsPromptCache: true,
        supportsGlobalEndpoint: true,
        inputPrice: 0.3,
        outputPrice: 2.5,
        thinkingConfig: {
            maxBudget: 24576,
            outputPrice: 3.5,
        },
    },

    "gemini-2.5-flash-lite-preview-06-17": {
        maxTokens: 64000,
        contextWindow: 1_000_000,
        supportsImages: true,
        supportsPromptCache: true,
        supportsGlobalEndpoint: true,
        inputPrice: 0.1,
        outputPrice: 0.4,
        cacheReadsPrice: 0.025,
        description: "Preview version - may not be available in all regions",
        thinkingConfig: {
            maxBudget: 24576,
        },
    },
    "gemini-2.0-flash-thinking-exp-01-21": {
        maxTokens: 65_536,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsPromptCache: false,
        supportsGlobalEndpoint: true,
        inputPrice: 0,
        outputPrice: 0,
    },
    "gemini-exp-1206": {
        maxTokens: 8192,
        contextWindow: 2_097_152,
        supportsImages: true,
        supportsPromptCache: false,
        inputPrice: 0,
        outputPrice: 0,
    },
    "gemini-1.5-flash-002": {
        maxTokens: 8192,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsPromptCache: true,
        inputPrice: 0.15,
        outputPrice: 0.6,
        cacheWritesPrice: 1.0,
        cacheReadsPrice: 0.0375,
        tiers: [
            {
                contextWindow: 128000,
                inputPrice: 0.075,
                outputPrice: 0.3,
                cacheReadsPrice: 0.01875,
            },
            {
                contextWindow: Infinity,
                inputPrice: 0.15,
                outputPrice: 0.6,
                cacheReadsPrice: 0.0375,
            },
        ],
    },
    "gemini-1.5-flash-exp-0827": {
        maxTokens: 8192,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsPromptCache: false,
        inputPrice: 0,
        outputPrice: 0,
    },
    "gemini-1.5-flash-8b-exp-0827": {
        maxTokens: 8192,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsPromptCache: false,
        inputPrice: 0,
        outputPrice: 0,
    },
    "gemini-1.5-pro-002": {
        maxTokens: 8192,
        contextWindow: 2_097_152,
        supportsImages: true,
        supportsPromptCache: false,
        inputPrice: 1.25,
        outputPrice: 5,
    },
    "gemini-1.5-pro-exp-0827": {
        maxTokens: 8192,
        contextWindow: 2_097_152,
        supportsImages: true,
        supportsPromptCache: false,
        inputPrice: 0,
        outputPrice: 0,
    },
} as const satisfies Record<string, ModelInfo>

export const vertexGlobalModels: Record<string, ModelInfo> = Object.fromEntries(
    Object.entries(vertexModels).filter(([_k, v]) => Object.hasOwn(v, "supportsGlobalEndpoint")),
) as Record<string, ModelInfo>
