schema: pokerheader.v1
project: pokertool
file: pokertool-frontend/src/.DS_Store
version: v28.0.0
last_commit: '2025-09-22T23:58:51.343154+00:00'
fixes:
- date: '2025-09-25'
  summary: Enhanced enterprise documentation and comprehensive unit tests added
